django_website/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
]

django_website/django_website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'blog/', include('blog.urls', namespace='blog')),
    url(r'', include('website_core.urls')),
]

django_website/website_core/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about.*$', views.about, name='about'),
    url(r'^contact.*$', views.contact, name='contact'),
    url(r'^404.*$', views.handler404, name='404'),
    url(r'^50.*$', views.handler500, name='500'),
]

django_website/blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

django_website/website_core/models.py
from django.db import models

# Create your models here.

django_website/blog/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Post

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by(
            '-published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

django_website/website_core/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.template import RequestContext

def index(request):
    return render(request, 'website_core/index.html', {})

def about(request):
    return render(request, 'website_core/about.html', {})

def contact(request):
    return render(request, 'website_core/contact.html', {})

def handler404(request):
    response = render_to_response('404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response

def handler500(request):
    response = render_to_response('500.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 500
    return response

django_website/blog/templates/blog/post_list.html
{% extends "website_core/base.html" %}

{% block content %}
  {% for post in posts %}
    <div class="post">
      <div class="date">
        <p>published: {{ post.published_date }}</p>
      </div class="date">
      <h2><a href="">{{ post.title }}</a></h2>
      <p>{{ post.text|linebreaks }}</p>
    </div class="post">
  {% endfor %}
{% endblock content %}

django_website/website_core/templates/website_core/about.html
{% extends "website_core/base.html" %}

{% block content %}
  <h1>About Us</h1>
{% endblock content %}

django_website/website_core/templates/website_core/base.html
{% load staticfiles %}

<html>

<head>
  <link rel="stylesheet"
        href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet"
        href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link rel="stylesheet" type="text/css"
        href="https://fonts.googleapis.com/css?family=Syncopate:700">
  <link rel="stylesheet"
        href="{% static "css/style.css" %}">

  <title>Site-wide Base.html</title>
</head>

<body>
  <div class="page-header">
    <h1><a href="{% url "index" %}">Site-Wide base.html</a></hi>
    <p><ul>
      <li><a href="{% url "index" %}">Home</a></li>
      <li><a href="{% url "blog:post_list" %}">Blog</a></li>
      <li><a href="{% url "about" %}">About Us</a></li>
      <li><a href="{% url "contact" %}">Contact Us</a></li>
    </ul></p>
  </div class="page-header">

  <div class="content container">
    <div class="row">
        <div class="col-md-8">
          {% block content %}
          {% endblock content %}
        </div class="col-md-8">
    </div class="row">
</div class="content container">

</body>

</html>

django_website/website_core/templates/website_core/contact.html
{% extends "website_core/base.html" %}

{% block content %}
  <h1>Contact Us</h1>
{% endblock content %}

django_website/website_core/templates/website_core/index.html
{% extends "website_core/base.html" %}

{% block content %}
  <h1>This is the Homepage!</h1>
{% endblock content %}